/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package tutorial7;

/**
 *
 * @author balth
 */

/**
 * @hidden
 * OrderException, which is an Exception that is created and thrown under any of the following conditions: 
 * A customer attempts to order more than four different items. 
 * A customer orders more than 100 of any item.
 * A customer enters an invalid item number. 
 * Also, catch the Exception generated by either of these conditions: 
 * A customer enters a nonnumeric character as the item number. 
 * A customer enters a nonnumeric character as the quantity. 
 * 
 */

public class OrderException extends java.io.IOException {
    public OrderException()
    {
        super("Error: Invalid Order");
    }
}
